module.exports={
    USER_COLLECTION:'user',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTION:'cart',
    MEN_COLLECTION:'men',
    WOMEN_COLLECTION:'women',
    BOYS_COLLECTION:'boys',
    GIRLS_COLLECTION:'girls',
    ORDER_COLLECTION:'order'
}